### ISSUE TITLE
SpaceMouse isn't being recognize though code is injected in TinkerCAD

### ISSUE THREAD

**Issue by ghost** [arpruss/spacemouse-tinkercad#2]

**Comment by arpruss** [comment]
Is this on MacOS? The latest MacOS has compatibility issues with the 3d connexion drivers. Go to this site and see if your SpaceMouse is being detected: https://gamepad-tester.com/

**Comment by ghost** [comment]
Hi - this is MacOS. It works for Catalina so apparently the issue is with BigSur. 

Thanks
